name: huggingface

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HFACE_TOKEN }}
        run: git push https://dk74433:$HFACE_TOKEN@huggingface.co/spaces/dk74433/News-Summarization-Text-to-Speech-App
